// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://safmxssjwrkjruiknuhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZm14c3Nqd3JranJ1aWtudWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzMwMTAsImV4cCI6MjA2MzAwOTAxMH0.KWmD_ELh9dQBlDVULfVR5wnoYs56aNMd96Y9cGYuyd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);